### ISSUE TITLE
Pre-defined inference bboxes

### ISSUE THREAD

**Issue by TMIU** [scuwyh2000/RandBox#11]
Thank you for your excellent work.
In your supplementary material, you described the pre-defined inference bboxes.
Are the pre-defined bboxes in the code and described in the paper the same?

**Comment by scuwyh2000** [comment]
> Thank you for your excellent work. In your supplementary material, you described the pre-defined inference bboxes. Are the pre-defined bboxes in the code and described in the paper the same?

Yes, you can find it from [line 120](https://github.com/scuwyh2000/RandBox/blob/main/randbox/detector.py#L120) to [line 127](https://github.com/scuwyh2000/RandBox/blob/main/randbox/detector.py#L127).

**Comment by TMIU** [comment]
I think self.x_dic has (cx, cy, w, h) bounding box format, and self.x_meta is [-2, -1.6, -1.2, -0.8, -0.4, 0, 0.4, 0.8, 1.2, 1.6].
So, after scaling (line 179), there are 0 height and 0 width bounding boxes. Isn't this different from the bounding box described in your material?

**Comment by scuwyh2000** [comment]
> I think self.x_dic has (cx, cy, w, h) bounding box format, and self.x_meta is [-2, -1.6, -1.2, -0.8, -0.4, 0, 0.4, 0.8, 1.2, 1.6]. So, after scaling (line 179), there are 0 height and 0 width bounding boxes. Isn't this different from the bounding box described in your material?

Correct, there are some 0 height and width, thanks for your findings. But it does not matter, we only want to emphasize that we use some gird-like boxes to do inference. And any other details you can follow the code as the accurate implement.
