### ISSUE TITLE
Data Preperation

### ISSUE THREAD

**Issue by JingfengYao** [scuwyh2000/RandBox#4]
Hi, thanks for your great work!

I am confused about the data preparation. According to your [get_started](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md#steps), the data are from MSCOCO. However, in the [./split](https://github.com/scuwyh2000/RandBox/tree/main/split) files, there are some image ids that seem not from COCO, such as ``001299`` or ``2008_008613``. 

May I ask where are they from?

**Comment by scuwyh2000** [comment]
The image data contain both VOC(07 and 12) and  MSCOCO, the image ids are either from MSCOCO or VOC.

**Comment by JingfengYao** [comment]
Thanks. BTW, is the code totally updated? I met some bugs when running it. 

``ModuleNotFoundError: No module named 'RandBox'``. I fixed it by renaming ``randbox`` folder to ``RandBox``. Then I met ``KeyError: 'Non-existent config key: MODEL.DiffusionDet'``. 

Before trying to solve it, I wanna make sure the repo is updated and tested to run successfully.

**Comment by scuwyh2000** [comment]
> Thanks. BTW, is the code totally updated? ([issue 1](https://github.com/scuwyh2000/RandBox/issues/1)) I met some bugs when running it.
> 
> `ModuleNotFoundError: No module named 'RandBox'`. I fixed it by renaming `randbox` folder to `RandBox`. Then I met `KeyError: 'Non-existent config key: MODEL.DiffusionDet'`.
> 
> Before trying to solve it, I wanna make sure the repo is updated and tested to run successfully.

Sorry for that, I have updated the config folder, you can pull the 'config/' folder and try again. If still any bugs, you can report here and I will reply as soon as possible. And I will check the code in following few days.

**Comment by scuwyh2000** [comment]
> Thanks. BTW, is the code totally updated? ([issue 1](https://github.com/scuwyh2000/RandBox/issues/1)) I met some bugs when running it.
> 
> `ModuleNotFoundError: No module named 'RandBox'`. I fixed it by renaming `randbox` folder to `RandBox`. Then I met `KeyError: 'Non-existent config key: MODEL.DiffusionDet'`.
> 
> Before trying to solve it, I wanna make sure the repo is updated and tested to run successfully.

I have updated and checked the current version. You can run it after confirming the environment and route are correct!

**Comment by JingfengYao** [comment]
Thanks a lot. But I still met some problems with multi-GPU training. When I set ``--num-gpus`` equals to 2 as ``run.sh`` and run ``train_net.py``, it's strange that the model is still training on a single GPU.

**Comment by rolsheng** [comment]
> Thanks a lot. But I still met some problems with multi-GPU training. When I set `--num-gpus` equals to 2 as `run.sh` and run `train_net.py`, it's strange that the model is still training on a single GPU.

I met the same question.

**Comment by feifeiobama** [comment]
> Thanks a lot. But I still met some problems with multi-GPU training. When I set `--num-gpus` equals to 2 as `run.sh` and run `train_net.py`, it's strange that the model is still training on a single GPU.

Have you found any fixes? I am facing the same problem.

**Comment by scuwyh2000** [comment]
Hi guys, I have solved this issue. You can update the new version of  '[./train_net.py](https://github.com/scuwyh2000/RandBox/blob/main/train_net.py)'. @feifeiobama @JingfengYao @rolsheng

**Comment by feifeiobama** [comment]
> Hi guys, I have solved this issue. You can update the new version of '[./train_net.py](https://github.com/scuwyh2000/RandBox/blob/main/train_net.py)'. @feifeiobama @JingfengYao @rolsheng

It's fixed, thank you so much!
