### ISSUE TITLE
Inconsistent evaluation

### ISSUE THREAD

**Issue by feifeiobama** [scuwyh2000/RandBox#5]
Your paper described the evaluation protocol as:
> the final predictions are the bboxes whose probability of belonging to a class in K ∪ {“unknown′′} are at least 0.1.

But your code uses a different threshold: https://github.com/scuwyh2000/RandBox/blob/a86be58f031f2567df82deaaf75cbb9f4b7ae86f/randbox/pascal_voc_evaluation.py#L90

**Comment by scuwyh2000** [comment]
> Your paper described the evaluation protocol as:
> 
> > the final predictions are the bboxes whose probability of belonging to a class in K ∪ {“unknown′′} are at least 0.1.
> 
> But your code uses a different threshold:
> 
> https://github.com/scuwyh2000/RandBox/blob/a86be58f031f2567df82deaaf75cbb9f4b7ae86f/randbox/pascal_voc_evaluation.py#L90

We used 0.15. And I will modify it in the newest arxiv version.

**Comment by feifeiobama** [comment]
Thank you for your clarification!
