### ISSUE TITLE
No such file or directory: 'datasets/test.txt'

### ISSUE THREAD

**Issue by YH-2023** [scuwyh2000/RandBox#6]
@scuwyh2000 你好
1.推理过程中报错:FileNotFoundError: [Errno 2] No such file or directory: 'datasets/test.txt',
https://github.com/scuwyh2000/RandBox/blob/3f32c05525697cbc2d87c1625fd555b9ed7c3e17/randbox/pascal_voc_evaluation.py#L54-L55
这里路径是不是不对
2.我发现会存在未知过度自信问题的,请问你是怎么解决未知过度自信问题的?

**Comment by scuwyh2000** [comment]
> @scuwyh2000 你好 1.推理过程中报错:FileNotFoundError: [Errno 2] No such file or directory: 'datasets/test.txt',
> 
> https://github.com/scuwyh2000/RandBox/blob/3f32c05525697cbc2d87c1625fd555b9ed7c3e17/randbox/pascal_voc_evaluation.py#L54-L55
> 
> 
> 这里路径是不是不对
> 2.我发现会存在未知过度自信问题的,请问你是怎么解决未知过度自信问题的?

1\ Please update the [pascal_voc_evaluation.py](https://github.com/scuwyh2000/RandBox/blob/main/randbox/pascal_voc_evaluation.py) and follow the [Getting Started with RandBox](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md). (Especially the Annotations/ under datasets/)
2\Can you clarify the '未知过度自信问题'?
