### ISSUE TITLE
match

### ISSUE THREAD

**Issue by YH-2023** [scuwyh2000/RandBox#8]
@scuwyh2000 
![image](https://github.com/scuwyh2000/RandBox/assets/59163676/d6e4caec-d965-40f4-bc60-c847b945dd1b)
预测过程中如果前景-未知的匹配分数比较高,以至于接近前景-已知的匹配分数,怎么区分这个是属于已知还是未知呢?进行二部匹配的时候会混淆已知和未知吗?会存在这样一种情况吗?

并且在推理过程中总是报错:
![image](https://github.com/scuwyh2000/RandBox/assets/59163676/ec439cac-15c8-441c-836f-47e2e3bdd933)

**Comment by scuwyh2000** [comment]
> @scuwyh2000 ![image](https://user-images.githubusercontent.com/59163676/269194124-d6e4caec-d965-40f4-bc60-c847b945dd1b.png) 预测过程中如果前景-未知的匹配分数比较高,以至于接近前景-已知的匹配分数,怎么区分这个是属于已知还是未知呢?进行二部匹配的时候会混淆已知和未知吗?会存在这样一种情况吗?
> 
> 并且在推理过程中总是报错: ![image](https://user-images.githubusercontent.com/59163676/269196295-ec439cac-15c8-441c-836f-47e2e3bdd933.png)

1\ Only unmatched proposal (meanwhile with high matching score) can be considered as 'unknown'. You can find the details in line [458](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L458) - [476](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L476).

2\Make sure you follow the [Getting Started with RandBox](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md) and confirm all the path is correct.

**Comment by YH-2023** [comment]
> > @scuwyh2000 ![image](https://user-images.githubusercontent.com/59163676/269194124-d6e4caec-d965-40f4-bc60-c847b945dd1b.png) 预测过程中如果前景-未知的匹配分数比较高,以至于接近前景-已知的匹配分数,怎么区分这个是属于已知还是未知呢?进行二部匹配的时候会混淆已知和未知吗?会存在这样一种情况吗?
> > 并且在推理过程中总是报错: ![image](https://user-images.githubusercontent.com/59163676/269196295-ec439cac-15c8-441c-836f-47e2e3bdd933.png)
> 
> 1\ Only unmatched proposal (meanwhile with high matching score) can be considered as 'unknown'. You can find the details in line [458](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L458) - [476](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L476).1\ 只有未匹配的提案（同时具有高匹配分数）才能被视为“未知”。您可以在第 458 - 476 行找到详细信息。
> 
> 2\Make sure you follow the [Getting Started with RandBox](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md) and confirm all the path is correct.2\确保您遵循 RandBox 入门并确认所有路径均正确。

还有一个疑惑就是,sparsercnn中是要训练270000次,而RandBox只需要训练20000次即可,这有什么依据吗?
再次感谢您的回复

**Comment by scuwyh2000** [comment]
> > > @scuwyh2000 ![image](https://user-images.githubusercontent.com/59163676/269194124-d6e4caec-d965-40f4-bc60-c847b945dd1b.png) 预测过程中如果前景-未知的匹配分数比较高,以至于接近前景-已知的匹配分数,怎么区分这个是属于已知还是未知呢?进行二部匹配的时候会混淆已知和未知吗?会存在这样一种情况吗?
> > > 并且在推理过程中总是报错: ![image](https://user-images.githubusercontent.com/59163676/269196295-ec439cac-15c8-441c-836f-47e2e3bdd933.png)
> > 
> > 
> > 1\ Only unmatched proposal (meanwhile with high matching score) can be considered as 'unknown'. You can find the details in line [458](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L458) - [476](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L476).1\ 只有未匹配的提案（同时具有高匹配分数）才能被视为“未知”。您可以在第 458 - 476 行找到详细信息。
> > 2\Make sure you follow the [Getting Started with RandBox](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md) and confirm all the path is correct.2\确保您遵循 RandBox 入门并确认所有路径均正确。
> 
> 还有个疑惑就是,sparsercnn中是要训练270000次,而RandBox在t1任务中只需要训练20000次即可,这有什么依据吗? loss_nc_ce和loss_ce的区别有什么区别?我看代码都一样啊 再次感谢您的回复

1\不确定你所说的270000次的出处。RandBox是训练至收敛。
2\nc_loss针对unknown和known，ce只针对known，可以说二者都是联合优化目标的一部分。

**Comment by YH-2023** [comment]
> > > > @scuwyh2000 ![image](https://user-images.githubusercontent.com/59163676/269194124-d6e4caec-d965-40f4-bc60-c847b945dd1b.png) 预测过程中如果前景-未知的匹配分数比较高,以至于接近前景-已知的匹配分数,怎么区分这个是属于已知还是未知呢?进行二部匹配的时候会混淆已知和未知吗?会存在这样一种情况吗?
> > > > 并且在推理过程中总是报错: ![image](https://user-images.githubusercontent.com/59163676/269196295-ec439cac-15c8-441c-836f-47e2e3bdd933.png)
> > > 
> > > 
> > > 1\ Only unmatched proposal (meanwhile with high matching score) can be considered as 'unknown'. You can find the details in line [458](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L458) - [476](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L476).1\ 只有未匹配的提案（同时具有高匹配分数）才能被视为“未知”。您可以在第 458 - 476 行找到详细信息。
> > > 2\Make sure you follow the [Getting Started with RandBox](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md) and confirm all the path is correct.2\确保您遵循 RandBox 入门并确认所有路径均正确。2\确保您遵循 RandBox 入门并确认所有路径均正确。2\确保您遵循 RandBox 入门并确认所有路径均正确。
> > 
> > 
> > 还有个疑惑就是,sparsercnn中是要训练270000次,而RandBox在t1任务中只需要训练20000次即可,这有什么依据吗? loss_nc_ce和loss_ce的区别有什么区别?我看代码都一样啊 再次感谢您的回复
> 
> 1\不确定你所说的270000次的出处。RandBox是训练至收敛。 2\nc_loss针对unknown和known，ce只针对known，可以说二者都是联合优化目标的一部分。

https://github.com/scuwyh2000/RandBox/blob/80521f418f0bd0a56a9b33fa892c97091b909eeb/configs/Base-RandBox.yaml#L22

**Comment by scuwyh2000** [comment]
> > > > > @scuwyh2000 ![image](https://user-images.githubusercontent.com/59163676/269194124-d6e4caec-d965-40f4-bc60-c847b945dd1b.png) 预测过程中如果前景-未知的匹配分数比较高,以至于接近前景-已知的匹配分数,怎么区分这个是属于已知还是未知呢?进行二部匹配的时候会混淆已知和未知吗?会存在这样一种情况吗?
> > > > > 并且在推理过程中总是报错: ![image](https://user-images.githubusercontent.com/59163676/269196295-ec439cac-15c8-441c-836f-47e2e3bdd933.png)
> > > > 
> > > > 
> > > > 1\ Only unmatched proposal (meanwhile with high matching score) can be considered as 'unknown'. You can find the details in line [458](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L458) - [476](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L476).1\ 只有未匹配的提案（同时具有高匹配分数）才能被视为“未知”。您可以在第 458 - 476 行找到详细信息。
> > > > 2\Make sure you follow the [Getting Started with RandBox](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md) and confirm all the path is correct.2\确保您遵循 RandBox 入门并确认所有路径均正确。2\确保您遵循 RandBox 入门并确认所有路径均正确。2\确保您遵循 RandBox 入门并确认所有路径均正确。
> > > 
> > > 
> > > 还有个疑惑就是,sparsercnn中是要训练270000次,而RandBox在t1任务中只需要训练20000次即可,这有什么依据吗? loss_nc_ce和loss_ce的区别有什么区别?我看代码都一样啊 再次感谢您的回复
> > 
> > 
> > 1\不确定你所说的270000次的出处。RandBox是训练至收敛。 2\nc_loss针对unknown和known，ce只针对known，可以说二者都是联合优化目标的一部分。
> 
> https://github.com/scuwyh2000/RandBox/blob/80521f418f0bd0a56a9b33fa892c97091b909eeb/configs/Base-RandBox.yaml#L22

这是基础配置文件，参考[detectron2](https://github.com/facebookresearch/detectron2)

**Comment by YH-2023** [comment]
> > > > > > @scuwyh2000 ![image](https://user-images.githubusercontent.com/59163676/269194124-d6e4caec-d965-40f4-bc60-c847b945dd1b.png) 预测过程中如果前景-未知的匹配分数比较高,以至于接近前景-已知的匹配分数,怎么区分这个是属于已知还是未知呢?进行二部匹配的时候会混淆已知和未知吗?会存在这样一种情况吗?
> > > > > > 并且在推理过程中总是报错: ![image](https://user-images.githubusercontent.com/59163676/269196295-ec439cac-15c8-441c-836f-47e2e3bdd933.png)
> > > > > 
> > > > > 
> > > > > 1\ Only unmatched proposal (meanwhile with high matching score) can be considered as 'unknown'. You can find the details in line [458](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L458) - [476](https://github.com/scuwyh2000/RandBox/blob/main/randbox/loss.py#L476).1\ 只有未匹配的提案（同时具有高匹配分数）才能被视为“未知”。您可以在第 458 - 476 行找到详细信息。
> > > > > 2\Make sure you follow the [Getting Started with RandBox](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md) and confirm all the path is correct.2\确保您遵循 RandBox 入门并确认所有路径均正确。2\确保您遵循 RandBox 入门并确认所有路径均正确。2\确保您遵循 RandBox 入门并确认所有路径均正确。
> > > > 
> > > > 
> > > > 还有个疑惑就是,sparsercnn中是要训练270000次,而RandBox在t1任务中只需要训练20000次即可,这有什么依据吗? loss_nc_ce和loss_ce的区别有什么区别?我看代码都一样啊 再次感谢您的回复
> > > 
> > > 
> > > 1\不确定你所说的270000次的出处。RandBox是训练至收敛。 2\nc_loss针对unknown和known，ce只针对known，可以说二者都是联合优化目标的一部分。
> > 
> > 
> > https://github.com/scuwyh2000/RandBox/blob/80521f418f0bd0a56a9b33fa892c97091b909eeb/configs/Base-RandBox.yaml#L22
> 
> 这是基础配置文件，参考[detectron2](https://github.com/facebookresearch/detectron2)

哦哦,我看sparsercnn的训练文件也是要训练270000次,好的感谢

**Comment by YH-2023** [comment]
我用的是ORE论文里面的数据集,ORE里面的数据集和本文的数据集我看是一样的,为什么还是报File "/home/randbox/randbox/pascal_voc_evaluation.py", line 457, in voc_eval
    R = class_recs[image_ids[d]]
KeyError: '6263'

**Comment by scuwyh2000** [comment]
> 我用的是ORE论文里面的数据集,ORE里面的数据集和本文的数据集我看是一样的,为什么还是报File "/home/randbox/randbox/pascal_voc_evaluation.py", line 457, in voc_eval R = class_recs[image_ids[d]] KeyError: '6263'

我认为你没有使用我的code，请确保按照[Getting Started with RandBox](https://github.com/scuwyh2000/RandBox/blob/main/GETTING_STARTED.md)的要求准备数据集并使用我的代码。我的代码中[第457行](https://github.com/scuwyh2000/RandBox/blob/main/randbox/pascal_voc_evaluation.py#L456)与你所列出的内容是不同的。

**Comment by YH-2023** [comment]
> 要求准备数据集并使用我的代码

 File "/home/work/randbox/randbox/pascal_voc_evaluation.py", line 457, in voc_eval
    R = class_recs[str(mapping[int(image_ids[d])])]
KeyError: '006263'
并且我把image_ids进行了打印,
![image](https://github.com/scuwyh2000/RandBox/assets/59163676/4565665a-aeb2-4ef5-8ddd-9219e56f83df)

**Comment by scuwyh2000** [comment]
> > 要求准备数据集并使用我的代码
> 
> 修改之后,还是报同样的错误,就是因为这个错误我才换ORE里面的代码,然后我现在又换回来了还是报这个错误 File "/home/randbox/randbox/pascal_voc_evaluation.py", line 457, in voc_eval R = class_recs[str(mapping[int(image_ids[d])])] KeyError: '006263' 并且我把image_ids进行了打印, ![image](https://user-images.githubusercontent.com/59163676/269804587-4565665a-aeb2-4ef5-8ddd-9219e56f83df.png) 难道是因为前面没有00的原因吗?应该是006263而不是6263吗?

你在datasets/下有Annotations/吗

**Comment by YH-2023** [comment]
> > > 要求准备数据集并使用我的代码
> > 
> > 
> > 修改之后,还是报同样的错误,就是因为这个错误我才换ORE里面的代码,然后我现在又换回来了还是报这个错误 File "/home/randbox/randbox/pascal_voc_evaluation.py", line 457, in voc_eval R = class_recs[str(mapping[int(image_ids[d])])] KeyError: '006263' 并且我把image_ids进行了打印, ![image](https://user-images.githubusercontent.com/59163676/269804587-4565665a-aeb2-4ef5-8ddd-9219e56f83df.png) 难道是因为前面没有00的原因吗?应该是006263而不是6263吗?
> 
> 你在datasets/下有Annotations/吗

![image](https://github.com/scuwyh2000/RandBox/assets/59163676/272b2368-2ccd-4a51-8143-8274b40ad167)
这是数据格式,

**Comment by scuwyh2000** [comment]
Datasets/Annotations/ 是否有这个文件夹

**Comment by scuwyh2000** [comment]
> > > > 要求准备数据集并使用我的代码
> > > 
> > > 
> > > 修改之后,还是报同样的错误,就是因为这个错误我才换ORE里面的代码,然后我现在又换回来了还是报这个错误 File "/home/randbox/randbox/pascal_voc_evaluation.py", line 457, in voc_eval R = class_recs[str(mapping[int(image_ids[d])])] KeyError: '006263' 并且我把image_ids进行了打印, ![image](https://user-images.githubusercontent.com/59163676/269804587-4565665a-aeb2-4ef5-8ddd-9219e56f83df.png) 难道是因为前面没有00的原因吗?应该是006263而不是6263吗?
> > 
> > 
> > 你在datasets/下有Annotations/吗
> 
> ![image](https://user-images.githubusercontent.com/59163676/269819681-272b2368-2ccd-4a51-8143-8274b40ad167.png) 这是数据格式, 我能够正常训练但是没有办法正常测试,按照ORE中的数据集训练数据和测试数据是在一起的,然后根据split进行的数据集划分

<img width="1009" alt="image" src="https://github.com/scuwyh2000/RandBox/assets/87008857/90b65847-8b42-46d0-aa22-009191e145e0">

**Comment by YH-2023** [comment]
> > > > > 要求准备数据集并使用我的代码
> > > > 
> > > > 
> > > > 修改之后,还是报同样的错误,就是因为这个错误我才换ORE里面的代码,然后我现在又换回来了还是报这个错误 File "/home/randbox/randbox/pascal_voc_evaluation.py", line 457, in voc_eval R = class_recs[str(mapping[int(image_ids[d])])] KeyError: '006263' 并且我把image_ids进行了打印, ![image](https://user-images.githubusercontent.com/59163676/269804587-4565665a-aeb2-4ef5-8ddd-9219e56f83df.png) 难道是因为前面没有00的原因吗?应该是006263而不是6263吗?
> > > 
> > > 
> > > 你在datasets/下有Annotations/吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/59163676/269819681-272b2368-2ccd-4a51-8143-8274b40ad167.png) 这是数据格式, 我能够正常训练但是没有办法正常测试,按照ORE中的数据集训练数据和测试数据是在一起的,然后根据split进行的数据集划分
> 
> <img alt="image" width="1009" src="https://user-images.githubusercontent.com/87008857/269847200-90b65847-8b42-46d0-aa22-009191e145e0.png">

哎呀没看到,我以为t1任务里面的annotations就可以了,我再试试,感谢感谢

**Comment by YH-2023** [comment]
@scuwyh2000 
 调整之后还是报这个错误:
File "/home/randbox/randbox/pascal_voc_evaluation.py", line 457, in voc_eval
    R = class_recs[image_ids[d]]
KeyError: '6263'
数据结构如下:
![image](https://github.com/scuwyh2000/RandBox/assets/59163676/0ef8b49e-25aa-4475-8b8d-ad6dc691c2cf)

**Comment by scuwyh2000** [comment]
> 感谢指点 ![image](https://user-images.githubusercontent.com/59163676/269857748-8e0d6534-3832-487a-84cb-7f2567743b32.png) 这是我复现出来的结果(用的是我重新训练之后的权重)和论文的结果还是有点出入的,这可能是什么原因造成的

1、目前没有其他报错了是吧？
2、这跟你的超参数设置、gpu型号等有关，你可以参考我给出的超参数，尝试使用不同的超参数进行训练。

**Comment by scuwyh2000** [comment]
> > > 感谢指点 ![image](https://user-images.githubusercontent.com/59163676/269857748-8e0d6534-3832-487a-84cb-7f2567743b32.png) 这是我复现出来的结果(用的是我重新训练之后的权重)和论文的结果还是有点出入的,这可能是什么原因造成的
> > 
> > 
> > 1、目前没有其他报错了是吧？ 2、这跟你的超参数设置、gpu型号等有关，你可以参考我给出的超参数，尝试使用不同的超参数进行训练。
> 
> 对的对的,非常感谢,现在可以正常测试了,超参数的话我是把代码下载下来之后直接就运行了没有修改超参数

你也可以尝试修改 [line458](https://github.com/scuwyh2000/RandBox/blob/main/randbox/config.py#L48) 为0，你也可以对比我已经训练好的模型https://github.com/scuwyh2000/RandBox/tree/main#models

**Comment by YH-2023** [comment]
> > > > 感谢指点 ![image](https://user-images.githubusercontent.com/59163676/269857748-8e0d6534-3832-487a-84cb-7f2567743b32.png) 这是我复现出来的结果(用的是我重新训练之后的权重)和论文的结果还是有点出入的,这可能是什么原因造成的
> > > 
> > > 
> > > 1、目前没有其他报错了是吧？ 2、这跟你的超参数设置、gpu型号等有关，你可以参考我给出的超参数，尝试使用不同的超参数进行训练。
> > 
> > 
> > 对的对的,非常感谢,现在可以正常测试了,超参数的话我是把代码下载下来之后直接就运行了没有修改超参数
> 
> 你也可以尝试修改 [line48](https://github.com/scuwyh2000/RandBox/blob/main/randbox/config.py#L48) 为0，你也可以对比我已经训练好的模型https://github.com/scuwyh2000/RandBox/tree/main#models

好的,我试试,感谢感谢

**Comment by YH-2023** [comment]
> > > > 感谢指点 ![image](https://user-images.githubusercontent.com/59163676/269857748-8e0d6534-3832-487a-84cb-7f2567743b32.png) 这是我复现出来的结果(用的是我重新训练之后的权重)和论文的结果还是有点出入的,这可能是什么原因造成的
> > > 
> > > 
> > > 1、目前没有其他报错了是吧？ 2、这跟你的超参数设置、gpu型号等有关，你可以参考我给出的超参数，尝试使用不同的超参数进行训练。
> > 
> > 
> > 对的对的,非常感谢,现在可以正常测试了,超参数的话我是把代码下载下来之后直接就运行了没有修改超参数
> 
> 你也可以尝试修改 [line48](https://github.com/scuwyh2000/RandBox/blob/main/randbox/config.py#L48) 为0，你也可以对比我已经训练好的模型https://github.com/scuwyh2000/RandBox/tree/main#models

当我今天在测试的时候也遇到了https://github.com/scuwyh2000/RandBox/issues/9#issue-1908259459同样的问题,上面的的结果是我在进行训练的时候结束之后,应该是最后的验证得到的结果

**Comment by scuwyh2000** [comment]
> > > > > 感谢指点 ![image](https://user-images.githubusercontent.com/59163676/269857748-8e0d6534-3832-487a-84cb-7f2567743b32.png) 这是我复现出来的结果(用的是我重新训练之后的权重)和论文的结果还是有点出入的,这可能是什么原因造成的
> > > > 
> > > > 
> > > > 1、目前没有其他报错了是吧？ 2、这跟你的超参数设置、gpu型号等有关，你可以参考我给出的超参数，尝试使用不同的超参数进行训练。
> > > 
> > > 
> > > 对的对的,非常感谢,现在可以正常测试了,超参数的话我是把代码下载下来之后直接就运行了没有修改超参数
> > 
> > 
> > 你也可以尝试修改 [line48](https://github.com/scuwyh2000/RandBox/blob/main/randbox/config.py#L48) 为0，你也可以对比我已经训练好的模型https://github.com/scuwyh2000/RandBox/tree/main#models
> 
> 当我今天在测试的时候也遇到了 [#9 (comment)](https://github.com/scuwyh2000/RandBox/issues/9#issue-1908259459) 同样的问题,上面的的结果是我在进行训练的时候结束之后,应该是最后的验证得到的结果

I think you can debug it (e.g. print the 'class_recs' dict), there may be a path issue. Because I clone my code and it can run successfully.

**Comment by YH-2023** [comment]
问一个题外话,如果batch_size变小,学习率用不用跟着同比例的缩小呢?为什么我把batch_size调小比大的batch_size训练的更快呢?如果只调节batch_size不调节学习率会影响最后的结果吗?

**Comment by AgreeW** [comment]
@YH-2023  你解决测试的问题了吗

**Comment by YH-2023** [comment]
> unknown和know

没,这两天在调试其他的代码,都是通过训练最后验证得到的结果,测试中存在这个错误好像不是路径的问题,

**Comment by AgreeW** [comment]
我也没解决，我怀疑是不是Annotations/ 里的*.xml 的问题 @YH-2023 @scuwyh2000

**Comment by YH-2023** [comment]
可以加个联系方式探讨一下吗?

**Comment by AgreeW** [comment]
+v: as923889498
